"""“Fix_first_and_last_name“

Revision ID: 4b5bd17e2c39
Revises: 12691d9d1bd2
Create Date: 2023-09-27 19:37:08.751172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5bd17e2c39'
down_revision: Union[str, None] = '12691d9d1bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sea_user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sea_user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sea_user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sea_user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
