"""Change Meet Model fields.

Revision ID: e66a9fb70867
Revises: 4b5bd17e2c39
Create Date: 2023-11-13 17:51:27.533823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66a9fb70867'
down_revision: Union[str, None] = '4b5bd17e2c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
